name: "Create Test Branch"
description: "Creates a unique, ephemeral branch in a remote repo."
inputs:
  repository:
    description: "Repository name with owner. For example, actions/checkout."
    required: true

  github-token:
    description: "The GITHUB_TOKEN to use for authorization."
    required: true

  branch-from:
    description: "The base branch to start from."
    default: ""
    required: false

  branch-prefix:
    description: "The prefix to use for generated branches."
    default: "ci/"
    required: false

  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository"
    default: "."
    required: false

  skip-cleanup:
    description: "If set to true, the branch will not be deleted at the end of the job."
    default: "false"
    required: false

  set-env-var:
    description: "If specified, sets this environment variable to the branch name in future steps."
    default: "TEST_BRANCH"
    required: false

outputs:
  branch:
    description: "The generated branch name."
    value: ${{ steps.vars.outputs.branch }}

  banner:
    description: "A Markdown banner to refer back to the current action."
    value: ${{ steps.vars.outputs.banner }}

runs:
  using: "composite"
  steps:
    - name: "Generate variables"
      id: vars
      shell: bash
      env:
        BRANCH_PREFIX: ${{ inputs.branch-prefix }}
      run: |-
        set -euo pipefail
        run_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        {
          printf "branch=%s%s\n" "$BRANCH_PREFIX" "$(uuidgen | tr -d '-')"
          printf "run-url=%s\n" "$run_url"
          printf "banner<<EOF\n"
          printf "> [!note]\n> "
          printf "%s\n" \
            "This branch was generated as part of a" \
            "[GitHub Actions run](${run_url})" \
            "in [${{ github.repository }}]" \
            "(${{ github.server_url }}/${{ github.repository }})."
          printf "\n---\nEOF\n"
        } >>"$GITHUB_OUTPUT"

    - name: "Checkout repo"
      id: checkout
      uses: actions/checkout@v7
      with:
        token: ${{ inputs.github-token || github.token }}
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.branch-from }}
        persist-credentials: true

    - name: "Setup git"
      id: setup-git
      uses: $/setup-git
      with:
        github-token: ${{ inputs.github-token || github.token }}
        scope: local

    - name: "Create branch"
      shell: bash
      env:
        REPO_PATH: "${{ inputs.path }}"
        BANNER: ${{ steps.vars.outputs.banner }}
        BRANCH: ${{ steps.vars.outputs.branch }}
        RUN_URL: ${{ steps.vars.outputs.run-url }}
      run: |-
        set -euo pipefail
        cd "$REPO_PATH"

        git checkout -b "$BRANCH"
        cat <(cat <<<"$BANNER") README.md > README.md.new
        mv README.md.new README.md
        git add -u
        git commit -m "ci: ${RUN_URL}"
        git push origin "$BRANCH"

    - name: "Set environment variable to newly-created branch"
      if: ${{ inputs.set-env-var != '' }}
      shell: bash
      env:
        BRANCH: ${{ steps.vars.outputs.branch }}
        SET_ENV_VAR: ${{ inputs.set-env-var }}
      run: |-
        printf "%s=%s\n" "$SET_ENV_VAR" "$BRANCH" >>"$GITHUB_ENV"

    - name: "Add cleanup hook"
      if: ${{ inputs.skip-cleanup != 'true' }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPOSITORY: ${{ inputs.repository }}
        BRANCH_PREFIX: ${{ steps.vars.outputs.branch }}
      uses: $/cleanup-hook
      with:
        run: |-
          set -euo pipefail
          bash "${GITHUB_ACTION_PATH}/cleanup/cleanup.sh"
