# This is a workflow used to validate the behavior of an action in this repo.
name: "Test Action: update-pr"

on:
  push:
    paths: &paths
      #
      # ----- BEGIN DETECTED DEPENDENCIES -----
      - actions-assert/action.yaml
      - actions-assert/asserts.sh
      - checkout-as-app/action.yaml
      - cleanup-hook/action-main.js
      - cleanup-hook/action-post.js
      - cleanup-hook/action.yaml
      - cleanup-hook/inputs.js
      - create-ci-branch/action.yaml
      - create-ci-branch/cleanup/action.yaml
      - create-ci-branch/cleanup/cleanup.sh
      - .github/workflows/test-action-actions-assert.yaml
      - .github/workflows/test-action-checkout-as-app.yaml
      - .github/workflows/test-action-cleanup-hook.yaml
      - .github/workflows/test-action-create-ci-branch.yaml
      - .github/workflows/test-action-update-pr.yaml
      - update-pr/action.yaml
      # ----- END DETECTED DEPENDENCIES -----
  pull_request:
    paths: *paths

env:
  TEST_REPO: eth-p/gh-actions-test-repo
  TEST_BRANCH: "" # set within jobs when running $/create-ci-branch

jobs:
  test-when-nothing-to-merge:
    name: "When Nothing to Merge"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-ci-branch
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          cleanup-after-job: true

      - name: "Setup"
        shell: bash
        run: |-
          set -euo pipefail
          git checkout -b "${TEST_BRANCH}-pr"
          git push origin "${TEST_BRANCH}-pr"

      - id: action
        uses: $/update-pr
        with:
          github-token: ${{ steps.test-branch.outputs.token }}
          repository: ${{ env.TEST_REPO }}
          base: ${{ steps.test-branch.outputs.branch }}
          head: ${{ steps.test-branch.outputs.branch }}-pr
          title: "Test PR: ${{ github.workflow }}"
          body: ${{ steps.test-branch.outputs.banner }}
          labels: ci

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Output 'number' is empty when no PR created"
              output: number
              is: empty

            - name: "Output 'url' is empty when no PR created"
              output: url
              is: empty

  test-updates-pr:
    name: "Updates Existing PR"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-ci-branch
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          cleanup-after-job: true

      - name: "Setup"
        shell: bash
        run: |-
          set -euo pipefail
          git checkout -b "${TEST_BRANCH}-pr"

          # Create a commit.
          touch new-file
          git add new-file
          git commit -m 'ci: Add new file'
          git push origin "${TEST_BRANCH}-pr"

      - name: "Create PR"
        id: create
        uses: $/update-pr
        with:
          github-token: ${{ steps.test-branch.outputs.token }}
          repository: ${{ env.TEST_REPO }}
          base: ${{ steps.test-branch.outputs.branch }}
          head: ${{ steps.test-branch.outputs.branch }}-pr
          labels: ci
          title: "${{ github.workflow }} - ${{ github.job }}"
          body: |-
            ${{ steps.test-branch.outputs.banner }}
            Job: ${{ github.job }}

      - name: "Update PR"
        id: action
        uses: $/update-pr
        with:
          github-token: ${{ steps.test-branch.outputs.token }}
          repository: ${{ env.TEST_REPO }}
          base: ${{ steps.test-branch.outputs.branch }}
          head: ${{ steps.test-branch.outputs.branch }}-pr
          title: "${{ github.workflow }} - ${{ github.job }} <UPDATED>"
          body: |-
            ${{ steps.test-branch.outputs.banner }}
            Job: ${{ github.job }} <UPDATED>
          labels: |-
            ci
            test

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        env:
          PR_NUMBER: "${{ steps.action.outputs.number }}"
          GH_TOKEN: "${{ steps.test-branch.outputs.token }}"
          REPO: "${{ env.TEST_REPO }}"
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "PR exists"
              is: [ok]
              run: 'gh pr view --repo "$REPO" "$PR_NUMBER"'

            - name: "PR title was updated"
              run: |-
                gh pr view --repo "$REPO" "$PR_NUMBER" --json title | jq -r '.title'
              is:
                - ok
                - contains: "<UPDATED>"

            - name: "PR body was updated"
              run: |-
                gh pr view --repo "$REPO" "$PR_NUMBER" --json body | jq -r '.body'
              is:
                - ok
                - contains: "<UPDATED>"

            - name: "Output 'number' is set"
              output: number
              is: not empty

            - name: "Output 'url' is set"
              output: url
              is: not empty

            - name: "Output 'title' is set"
              output: title
              is: not empty

            - name: "Output 'body-file' is set"
              output: body-file
              is: not empty


  test-creates-pr:
    name: "Creates New PR"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-ci-branch
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          cleanup-after-job: true

      - name: "Setup"
        shell: bash
        run: |-
          set -euo pipefail
          git checkout -b "${TEST_BRANCH}-pr"

          # Create a commit.
          touch new-file
          git add new-file
          git commit -m 'ci: Add new file'
          git push origin "${TEST_BRANCH}-pr"

      - id: action
        uses: $/update-pr
        with:
          github-token: ${{ steps.test-branch.outputs.token }}
          repository: ${{ env.TEST_REPO }}
          base: ${{ steps.test-branch.outputs.branch }}
          head: ${{ steps.test-branch.outputs.branch }}-pr
          labels: ci
          title: "${{ github.workflow }} - ${{ github.job }}"
          body: |-
            ${{ steps.test-branch.outputs.banner }}
            Job: ${{ github.job }}

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        env:
          PR_NUMBER: "${{ steps.action.outputs.number }}"
          GH_TOKEN: "${{ steps.test-branch.outputs.token }}"
          REPO: "${{ env.TEST_REPO }}"
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "PR exists"
              is: [ok]
              run: 'gh pr view --repo "$REPO" "$PR_NUMBER"'

            - name: "Output 'number' is set"
              output: number
              is: not empty

            - name: "Output 'url' is set"
              output: url
              is: not empty

            - name: "Output 'title' is set"
              output: title
              is: not empty

            - name: "Output 'body-file' is set"
              output: body-file
              is: not empty
