# This is a workflow used to validate the behavior of an action in this repo.
name: "Test Workflow: run-package-update-scripts"

on:
  push:
    paths: &paths
      #
      # ----- BEGIN DETECTED DEPENDENCIES -----
      - checkout-as-app/action.yaml
      - cleanup-hook/action-main.js
      - cleanup-hook/action-post.js
      - cleanup-hook/action.yaml
      - cleanup-hook/inputs.js
      - create-ci-branch/action.yaml
      - create-ci-branch/cleanup/action.yaml
      - create-ci-branch/cleanup/cleanup.sh
      - .github/workflows/run-package-update-scripts.yaml
      - .github/workflows/test-action-checkout-as-app.yaml
      - .github/workflows/test-action-cleanup-hook.yaml
      - .github/workflows/test-action-create-ci-branch-cleanup.yaml
      - .github/workflows/test-action-create-ci-branch.yaml
      - .github/workflows/test-action-nix-flake-develop.yaml
      - .github/workflows/test-action-rebase-branch.yaml
      - .github/workflows/test-action-update-pr.yaml
      - .github/workflows/test-workflow-run-package-update-scripts.yaml
      - nix-flake-develop/action.yaml
      - rebase-branch/action.yaml
      - update-pr/action.yaml
      # ----- END DETECTED DEPENDENCIES -----
  pull_request:
    paths: *paths

env:
  TEST_REPO: &test-repo "eth-p/gh-actions-test-repo"
  TEST_BRANCH: "" # set within jobs when running $/create-ci-branch

jobs:
  test-when-has-updates-setup:
    name: "When Has Updates (Setup)"
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.test-branch.outputs.branch }}
      banner: ${{ steps.test-branch.outputs.banner }}
    steps:
      - id: test-branch
        uses: $/create-ci-branch
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          cleanup-after-job: false

      - name: "Setup"
        shell: bash
        run: |-
          set -euo pipefail

          # Create the scripts branch.
          git checkout -b "${TEST_BRANCH}-scripts"
          for script in foo bar; do
            printf "touch %q\ngit add %q\ngit commit -m %q" \
              "$script" "$script" "update($script): pretend update" \
              >"${script}.sh"

            git add "${script}.sh"
          done

          git commit -m 'ci: Add scripts for run-package-update-scripts'
          git push origin "${TEST_BRANCH}-scripts"

  test-when-has-updates-run:
    name: "When Has Updates (Run)"
    needs:
      - test-when-has-updates-setup
    uses: $/.github/workflows/run-package-update-scripts.yaml
    permissions:
      contents: write
      pull-requests: write
    secrets:
      ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
      ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
    with:
      auth-with-ghapp: true
      repository: *test-repo
      base-branch: ${{ needs.test-when-has-updates-setup.outputs.branch }}
      pr-branch: ${{ needs.test-when-has-updates-setup.outputs.branch }}-pr
      script-branch:  ${{ needs.test-when-has-updates-setup.outputs.branch }}-scripts
      scripts: |-
        foo
        bar
      script-exec: |-
        bash "${SCRIPTS_WORKSPACE}/${SCRIPT}.sh"
      pr-title: "Test run-package-update-scripts workflow"
      pr-body: ${{ needs.test-when-has-updates-setup.outputs.banner }}
      pr-labels: ci

  test-when-has-updates:
    name: "When Has Updates (Assert)"
    runs-on: ubuntu-latest
    needs:
      - test-when-has-updates-setup
      - test-when-has-updates-run
    steps:
      - uses: $/checkout-as-app
        id: checkout
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          ref: ${{ needs.test-when-has-updates-setup.outputs.branch }}-pr

      - name: "Assert: Has changes from foo script"
        env: { BRANCH: "${{ needs.test-when-has-updates-setup.outputs.branch }}" }
        shell: bash
        run: |-
          set -euo pipefail
          test -f foo

      - name: "Assert: Has changes from bar script"
        env: { BRANCH: "${{ needs.test-when-has-updates-setup.outputs.branch }}" }
        shell: bash
        run: |-
          set -euo pipefail
          test -f bar

      - name: "Assert: Has pull request"
        env:
          GH_TOKEN: ${{ steps.checkout.outputs.token }}
        shell: bash
        run: |-
          set -euo pipefail
          gh pr view

  test-when-has-updates-cleanup:
    name: "When Has Updates (Cleanup)"
    runs-on: ubuntu-latest
    if: "${{ always() }}"
    needs:
      - test-when-has-updates-setup
      - test-when-has-updates-run
      - test-when-has-updates
    steps:
      - uses: $/create-ci-branch/cleanup
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          branch: ${{ needs.test-when-has-updates-setup.outputs.branch }}
