# This is a workflow used to validate the behavior of an action in this repo.
name: "Test Action: create-ci-branch"

on:
  push:
    paths: &paths
      #
      # ----- BEGIN DETECTED DEPENDENCIES -----
      - actions-assert/action.yaml
      - actions-assert/asserts.sh
      - create-ci-branch/as-app/action.yaml
      - .github/workflows/test-action-actions-assert.yaml
      - .github/workflows/test-action-create-ci-branch-as-app.yaml
      - .github/workflows/test-action-create-ci-branch.yaml
      # ----- END DETECTED DEPENDENCIES -----
  pull_request:
    paths: *paths

env:
  TEST_REPO: eth-p/gh-actions-test-repo

jobs:
  test-with-defaults:
    name: "Create CI Branch Works"
    runs-on: ubuntu-latest
    steps:
      - id: action
        uses: $/create-ci-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Checks out repo"
              is: [ok, not empty]
              run: 'git rev-parse HEAD'

            - name: "Repo is cloned shallow"
              run: 'git rev-parse --is-shallow-repository'
              is:
                - ok
                - equal: true

            - name: "Branch no exists on remote"
              is: [ok, not empty]
              run: 'git ls-remote origin "refs/heads/${TEST_BRANCH}"'

            - name: "Output 'branch' is not empty"
              output: branch
              is: not empty

            - name: "Output 'banner' is not empty"
              output: banner
              is: not empty

            - name: "Output 'token' is not empty"
              output: token
              is: not empty

            - name: "Sets 'TEST_BRANCH' environment variable"
              var: TEST_BRANCH
              is: not empty

  test-cleanup-setup:
    name: "Cleanup Hook (Setup)"
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.test-branch.outputs.branch }}
    steps:
      - id: test-branch
        uses: $/create-ci-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}

  test-cleanup:
    name: "Cleanup Hook"
    needs: [test-cleanup-setup]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        id: checkout
        uses: $/create-ci-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        env: { TEST_BRANCH: "${{ needs.test-cleanup-setup.outputs.branch }}" }
        with:
          asserts: |-
            - name: "Branch no longer exists on remote"
              is: [ok, empty]
              run: 'git ls-remote origin "refs/heads/${TEST_BRANCH}"'
