# This is a workflow used to validate the behavior of an action in this repo.
name: "Test Action: create-test-branch/cleanup"

on:
  push:
    paths: &paths
      #
      # ----- BEGIN DETECTED DEPENDENCIES -----
      - actions-assert/action.yaml
      - actions-assert/asserts.sh
      - cleanup-hook/action-main.js
      - cleanup-hook/action-post.js
      - cleanup-hook/action.yaml
      - cleanup-hook/inputs.js
      - create-test-branch/action.yaml
      - create-test-branch/as-app/action.yaml
      - create-test-branch/cleanup/action.yaml
      - create-test-branch/cleanup/cleanup.sh
      - .github/workflows/test-action-actions-assert.yaml
      - .github/workflows/test-action-cleanup-hook.yaml
      - .github/workflows/test-action-create-test-branch-as-app.yaml
      - .github/workflows/test-action-create-test-branch-cleanup.yaml
      - .github/workflows/test-action-create-test-branch.yaml
      - .github/workflows/test-action-setup-git.yaml
      - setup-git/action.yaml
      # ----- END DETECTED DEPENDENCIES -----
  pull_request:
    paths: *paths

env:
  TEST_REPO: eth-p/gh-actions-test-repo

jobs:
  test-one-branch:
    name: "Deletes Created Branch"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-test-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          skip-cleanup: true

      - id: action
        uses: $/create-test-branch/cleanup
        with:
          repository: ${{ env.TEST_REPO }}
          github-token: ${{ steps.test-branch.outputs.token }}
          branch: ${{ steps.test-branch.outputs.branch }}

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Branch no longer exists on remote"
              is: [ok, empty]
              run: 'git ls-remote origin "refs/heads/${TEST_BRANCH}"'

            - name: "Output 'count' matches number of deleted branches"
              output: count
              is:
                - equal: "1"

            - name: "Output 'branches' contains the deleted branch"
              output: branches
              is:
                - equal: "${{ steps.test-branch.outputs.branch }}"

  test-extra-branches:
    name: "Deletes Additional Branches"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-test-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          skip-cleanup: true

      - name: Create an extra branch
        shell: bash
        run: |-
          git checkout -b "${TEST_BRANCH}-extra"
          git push origin "${TEST_BRANCH}-extra"

      - id: action
        uses: $/create-test-branch/cleanup
        with:
          repository: ${{ env.TEST_REPO }}
          github-token: ${{ steps.test-branch.outputs.token }}
          branch: ${{ steps.test-branch.outputs.branch }}

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Branch no longer exists on remote"
              is: [ok, empty]
              run: 'git ls-remote origin "refs/heads/${TEST_BRANCH}"'

            - name: "Extra branch no longer exists on remote"
              is: [ok, empty]
              run: 'git ls-remote origin "refs/heads/${TEST_BRANCH}-extra"'

            - name: "Output 'count' matches number of deleted branches"
              output: count
              is:
                - equal: "2"

            - name: "Output 'branches' contains the deleted branches"
              output: branches
              is:
                - contains-line: "${{ steps.test-branch.outputs.branch }}"
                - contains-line: "${{ steps.test-branch.outputs.branch }}-extra"
