# This is a workflow used to validate the behavior of an action in this repo.
name: "Test Action: checkout-as-app"

on:
  push:
    paths: &paths
      #
      # ----- BEGIN DETECTED DEPENDENCIES -----
      - actions-assert/action.yaml
      - actions-assert/asserts.sh
      - checkout-as-app/action.yaml
      - .github/workflows/test-action-actions-assert.yaml
      - .github/workflows/test-action-checkout-as-app.yaml
      # ----- END DETECTED DEPENDENCIES -----
  pull_request:
    paths: *paths

env:
  TEST_REPO: eth-p/gh-actions-test-repo

jobs:
  test-with-defaults:
    name: "Checkout Works"
    runs-on: ubuntu-latest
    steps:
      - id: action
        uses: $/checkout-as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Repo is cloned"
              is: [ok, not empty]
              run: 'git rev-parse HEAD'

            - name: "Repo is shallow"
              run: 'git rev-parse --is-shallow-repository'
              is:
                - ok
                - equal: true

            - name: "Git user.name configured"
              is: [ok, not empty]
              run: 'git config --local user.name'

            - name: "Git user.email configured"
              is: [ok, not empty]
              run: 'git config --local user.email'

            - name: "Output 'git-name' is set"
              output: git-name
              is: not empty

            - name: "Output 'git-email' is set"
              output: git-email
              is: not empty

            - name: "Output 'token' is set"
              output: token
              is: not empty
