# This is a workflow used to validate the behavior of an action in this repo.
name: "Test Action: nix-flake-develop"

on:
  push:
    paths: &paths
      #
      # ----- BEGIN DETECTED DEPENDENCIES -----
      - actions-assert/action.yaml
      - actions-assert/asserts.sh
      - .github/workflows/test-action-actions-assert.yaml
      - .github/workflows/test-action-nix-flake-develop.yaml
      - nix-flake-develop/action.yaml
      # ----- END DETECTED DEPENDENCIES -----
  pull_request:
    paths: *paths

env:
  TEST_REPO: eth-p/gh-actions-test-repo

jobs:
  test-with-defaults:
    name: "Test Develop Profile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - id: action
        uses: $/nix-flake-develop
        with:
          flake: ./test-data/nix-flake

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        env: { ACTIVATE_BASH: "${{ steps.action.outputs.activate-bash }}" }
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Output 'activate-bash' is not empty"
              output: activate-bash
              is: not empty

            - name: "Can source 'activate-bash' to enter develop shell"
              run: 'source "$ACTIVATE_BASH"'
              is: [ok]

            - name: "PATH is updated to have executables from develop shell"
              run: 'hello'
              is: [ok]
