# This is a workflow used to validate the behavior of an action in this repo.
name: "Test Action: update-pr"

on:
  push:
    paths: &paths
      #
      # ----- BEGIN DETECTED DEPENDENCIES -----
      - checkout-as-app/action.yaml
      - cleanup-hook/action-main.js
      - cleanup-hook/action-post.js
      - cleanup-hook/action.yaml
      - cleanup-hook/inputs.js
      - create-ci-branch/action.yaml
      - create-ci-branch/cleanup/action.yaml
      - create-ci-branch/cleanup/cleanup.sh
      - .github/workflows/test-action-checkout-as-app.yaml
      - .github/workflows/test-action-cleanup-hook.yaml
      - .github/workflows/test-action-create-ci-branch.yaml
      - .github/workflows/test-action-update-pr.yaml
      - update-pr/action.yaml
      # ----- END DETECTED DEPENDENCIES -----
  pull_request:
    paths: *paths

env:
  TEST_REPO: eth-p/gh-actions-test-repo
  TEST_BRANCH: "" # set within jobs when running $/create-ci-branch

jobs:
  test-when-nothing-to-merge:
    name: "When Nothing to Merge"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-ci-branch
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          cleanup-after-job: true

      - name: "Setup"
        shell: bash
        run: |-
          set -euo pipefail
          git checkout -b "${TEST_BRANCH}-pr"
          git push origin "${TEST_BRANCH}-pr"

      - id: action
        uses: $/update-pr
        with:
          github-token: ${{ steps.test-branch.outputs.token }}
          repository: ${{ env.TEST_REPO }}
          base: ${{ steps.test-branch.outputs.branch }}
          head: ${{ steps.test-branch.outputs.branch }}-pr
          title: "Test PR: ${{ github.workflow }}"
          body: ${{ steps.test-branch.outputs.banner }}
          labels: ci

      - name: "Output: number (should be empty)"
        shell: bash
        env: { OUTPUT: "${{ steps.action.outputs.number }}" }
        run: |-
          set -euo pipefail
          test -z "$OUTPUT"

      - name: "Output: url (should be empty)"
        shell: bash
        env: { OUTPUT: "${{ steps.action.outputs.url }}" }
        run: |-
          set -euo pipefail
          test -z "$OUTPUT"

  test-updates-pr:
    name: "Updates Existing PR"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-ci-branch
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          cleanup-after-job: true

      - name: "Setup"
        shell: bash
        run: |-
          set -euo pipefail
          git checkout -b "${TEST_BRANCH}-pr"

          # Create a commit.
          touch new-file
          git add new-file
          git commit -m 'ci: Add new file'
          git push origin "${TEST_BRANCH}-pr"

      - name: "Create PR"
        id: create
        uses: $/update-pr
        with:
          github-token: ${{ steps.test-branch.outputs.token }}
          repository: ${{ env.TEST_REPO }}
          base: ${{ steps.test-branch.outputs.branch }}
          head: ${{ steps.test-branch.outputs.branch }}-pr
          labels: ci
          title: "${{ github.workflow }} - ${{ github.job }}"
          body: |-
            ${{ steps.test-branch.outputs.banner }}
            Job: ${{ github.job }}

      - name: "Update PR"
        id: action
        uses: $/update-pr
        with:
          github-token: ${{ steps.test-branch.outputs.token }}
          repository: ${{ env.TEST_REPO }}
          base: ${{ steps.test-branch.outputs.branch }}
          head: ${{ steps.test-branch.outputs.branch }}-pr
          title: "${{ github.workflow }} - ${{ github.job }} <UPDATED>"
          body: |-
            ${{ steps.test-branch.outputs.banner }}
            Job: ${{ github.job }} <UPDATED>
          labels: |-
            ci
            test

      - name: "Assert: PR Exists"
        shell: bash
        env:
          PR_NUMBER: "${{ steps.action.outputs.number }}"
          GH_TOKEN: "${{ steps.test-branch.outputs.token }}"
          REPO: "${{ env.TEST_REPO }}"
        run: |-
          set -euo pipefail
          gh pr view --repo "$REPO" "$PR_NUMBER"

      - name: "Assert: PR Title Updated"
        shell: bash
        env:
          PR_NUMBER: "${{ steps.action.outputs.number }}"
          GH_TOKEN: "${{ steps.test-branch.outputs.token }}"
          REPO: "${{ env.TEST_REPO }}"
        run: |-
          set -euo pipefail
          title=$(gh pr view --repo "$REPO" "$PR_NUMBER" --json title | jq -r '.title')
          sed 's/^/│ /' <<<"$title"
          grep -F "<UPDATED>" <<<"$title"

      - name: "Assert: PR Body Updated"
        shell: bash
        env:
          PR_NUMBER: "${{ steps.action.outputs.number }}"
          GH_TOKEN: "${{ steps.test-branch.outputs.token }}"
          REPO: "${{ env.TEST_REPO }}"
        run: |-
          set -euo pipefail
          title=$(gh pr view --repo "$REPO" "$PR_NUMBER" --json body | jq -r '.body')
          sed 's/^/│ /' <<<"$title"
          grep -F "<UPDATED>" <<<"$title"

      - name: "Output: number"
        shell: bash
        env: { OUTPUT: "${{ steps.action.outputs.number }}" }
        run: |-
          set -euo pipefail
          test -n "$OUTPUT"

      - name: "Output: url"
        shell: bash
        env: { OUTPUT: "${{ steps.action.outputs.url }}" }
        run: |-
          set -euo pipefail
          test -n "$OUTPUT"

      - name: "Output: title"
        shell: bash
        env: { OUTPUT: "${{ steps.action.outputs.title }}" }
        run: |-
          set -euo pipefail
          test -n "$OUTPUT"

      - name: "Output: body-file"
        shell: bash
        env: { OUTPUT: "${{ steps.action.outputs.body-file }}" }
        run: |-
          set -euo pipefail
          test -n "$OUTPUT"
          test "$(wc -c <"$OUTPUT")" -ne 0

  test-creates-pr:
    name: "Creates New PR"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-ci-branch
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}
          cleanup-after-job: true

      - name: "Setup"
        shell: bash
        run: |-
          set -euo pipefail
          git checkout -b "${TEST_BRANCH}-pr"

          # Create a commit.
          touch new-file
          git add new-file
          git commit -m 'ci: Add new file'
          git push origin "${TEST_BRANCH}-pr"

      - id: action
        uses: $/update-pr
        with:
          github-token: ${{ steps.test-branch.outputs.token }}
          repository: ${{ env.TEST_REPO }}
          base: ${{ steps.test-branch.outputs.branch }}
          head: ${{ steps.test-branch.outputs.branch }}-pr
          labels: ci
          title: "${{ github.workflow }} - ${{ github.job }}"
          body: |-
            ${{ steps.test-branch.outputs.banner }}
            Job: ${{ github.job }}

      - name: "Output: number"
        shell: bash
        env: { OUTPUT: "${{ steps.action.outputs.number }}" }
        run: |-
          set -euo pipefail
          test -n "$OUTPUT"

      - name: "Output: url"
        shell: bash
        env: { OUTPUT: "${{ steps.action.outputs.url }}" }
        run: |-
          set -euo pipefail
          test -n "$OUTPUT"
