# This is a workflow used to validate the behavior of an action in this repo.
name: "Test Action: setup-git"

on:
  push:
    paths: &paths
      #
      # ----- BEGIN DETECTED DEPENDENCIES -----
      - actions-assert/action.yaml
      - actions-assert/asserts.sh
      - .github/workflows/test-action-actions-assert.yaml
      - .github/workflows/test-action-setup-git.yaml
      - setup-git/action.yaml
      # ----- END DETECTED DEPENDENCIES -----
  pull_request:
    paths: *paths

env:
  TEST_REPO: eth-p/gh-actions-test-repo

jobs:
  test-detect-actions-info:
    name: "Detects from GITHUB_TOKEN"
    runs-on: ubuntu-latest
    steps:
      - id: action
        uses: $/setup-git

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Git user.name configured"
              is: [ok, not empty]
              run: 'git config user.name'

            - name: "Git user.email configured"
              is: [ok, not empty]
              run: 'git config user.email'

            - name: "Output 'git-user-name' is set"
              output: git-user-name
              is: not empty

            - name: "Output 'git-user-email' is set"
              output: git-user-email
              is: not empty

  test-detect-app-info:
    name: "Detects from GitHub App"
    runs-on: ubuntu-latest
    steps:
      - name: "Get GitHub Token"
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repositories: ${{ env.TEST_REPO }}
          skip-token-revoke: true

      - id: action
        uses: $/setup-git
        with:
          github-token: ${{ steps.app-token.outputs.token }}

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Git user.name configured"
              is: [ok, not empty]
              run: 'git config user.name'

            - name: "Git user.email configured"
              is: [ok, not empty]
              run: 'git config user.email'

            - name: "Output 'git-user-name' is set"
              output: git-user-name
              is: not empty

            - name: "Output 'git-user-email' is set"
              output: git-user-email
              is: not empty

  test-scope-local:
    name: "Scoped to local repo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - id: action
        uses: $/setup-git
        with:
          scope: local

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Git user.name configured"
              is: [ok, not empty]
              run: 'git config --local user.name'

            - name: "Git user.email configured"
              is: [ok, not empty]
              run: 'git config --local user.email'

            - name: "Output 'git-user-name' is set"
              output: git-user-name
              is: not empty

            - name: "Output 'git-user-email' is set"
              output: git-user-email
              is: not empty

  test-scope-global:
    name: "Scoped to global git config"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - id: action
        uses: $/setup-git
        with:
          scope: global

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Git user.name configured"
              is: [ok, not empty]
              run: 'git config --global user.name'

            - name: "Git user.email configured"
              is: [ok, not empty]
              run: 'git config --global user.email'

            - name: "Output 'git-user-name' is set"
              output: git-user-name
              is: not empty

            - name: "Output 'git-user-email' is set"
              output: git-user-email
              is: not empty
