# This is a workflow used to validate the behavior of an action in this repo.
name: "Test Action: rebase-branch"

on:
  push:
    paths: &paths
      #
      # ----- BEGIN DETECTED DEPENDENCIES -----
      - actions-assert/action.yaml
      - actions-assert/asserts.sh
      - cleanup-hook/action-main.js
      - cleanup-hook/action-post.js
      - cleanup-hook/action.yaml
      - cleanup-hook/inputs.js
      - create-test-branch/action.yaml
      - create-test-branch/as-app/action.yaml
      - create-test-branch/cleanup/action.yaml
      - create-test-branch/cleanup/cleanup.sh
      - .github/workflows/test-action-actions-assert.yaml
      - .github/workflows/test-action-cleanup-hook.yaml
      - .github/workflows/test-action-create-test-branch-as-app.yaml
      - .github/workflows/test-action-create-test-branch.yaml
      - .github/workflows/test-action-rebase-branch.yaml
      - .github/workflows/test-action-setup-git.yaml
      - rebase-branch/action.yaml
      - setup-git/action.yaml
      # ----- END DETECTED DEPENDENCIES -----
  pull_request:
    paths: *paths

env:
  TEST_REPO: eth-p/gh-actions-test-repo
  TEST_BRANCH: "" # set within jobs when running $/create-ci-branch

jobs:
  test-when-diverged-safely:
    name: "When Diverged From Base"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-test-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}

      - name: "Setup"
        shell: bash
        run: |-
          set -euo pipefail
          git checkout -b "${TEST_BRANCH}-target"

          # Move base branch ahead of target branch
          git checkout "${TEST_BRANCH}"
          echo "Test" >file-in-base.txt
          git add file-in-base.txt
          git commit -m "Add file in base"
          git push origin "${TEST_BRANCH}"

          # Move target branch ahead of common ancestor
          git checkout "${TEST_BRANCH}-target"
          echo "Test" >file-in-target.txt
          git add file-in-target.txt
          git commit -m "Add file in target"
          git push origin "${TEST_BRANCH}-target"

      - name: "Remove local branches"
        shell: bash
        run: |-
          set -euo pipefail
          git fetch --depth=1 origin master
          git checkout master
          git branch -D \
            "${TEST_BRANCH}" \
            "${TEST_BRANCH}-target"

      - id: action
        uses: $/rebase-branch
        with:
          base: ${{ steps.test-branch.outputs.branch }}
          branch: ${{ steps.test-branch.outputs.branch }}-target
          create-branch: false

      - name: "Fetch and checkout rebased branch"
        shell: bash
        run: |-
          set -euo pipefail
          git fetch origin "${TEST_BRANCH}" "${TEST_BRANCH}-target"
          git checkout "refs/remotes/origin/${TEST_BRANCH}-target"

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Changes from base branch were kept"
              run: 'test -e file-in-base.txt'
              is: ok

            - name: "Changes from target branch were kept"
              run: 'test -e file-in-target.txt'
              is: ok

            - name: "Base branch is ancestor of target branch"
              is: ok
              run: |-
                git merge-base --is-ancestor \
                  "refs/remotes/origin/${TEST_BRANCH}" \
                  "refs/remotes/origin/${TEST_BRANCH}-target"

  test-when-behind:
    name: "When Behind Base"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-test-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}

      - name: "Setup"
        id: setup
        shell: bash
        run: |-
          set -euo pipefail
          git checkout -b "${TEST_BRANCH}-target"
          git push origin "${TEST_BRANCH}-target"

          # Move base branch ahead of target branch
          git checkout "${TEST_BRANCH}"
          echo "Test" >file.txt
          git add file.txt
          git commit -m "Add file"
          git push origin "${TEST_BRANCH}"

          printf "commit=%s\n" "$(git rev-parse HEAD)" >>"$GITHUB_OUTPUT"

      - name: "Remove local branches"
        shell: bash
        run: |-
          set -euo pipefail
          git fetch --depth=1 origin master
          git checkout master
          git branch -D \
            "${TEST_BRANCH}" \
            "${TEST_BRANCH}-target"

      - id: action
        uses: $/rebase-branch
        with:
          base: ${{ steps.test-branch.outputs.branch }}
          branch: ${{ steps.test-branch.outputs.branch }}-target
          create-branch: false

      - name: "Fetch and checkout rebased branch"
        shell: bash
        run: |-
          set -euo pipefail
          git fetch origin "${TEST_BRANCH}" "${TEST_BRANCH}-target"
          git checkout "refs/remotes/origin/${TEST_BRANCH}-target"

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        env: { BASE_COMMIT: "${{ steps.setup.outputs.commit }}" }
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Changes from base branch were kept"
              run: 'test -e file.txt'
              is: ok

            - name: "Base branch is ancestor of target branch"
              is: ok
              run: |-
                git merge-base --is-ancestor \
                  "${BASE_COMMIT}" \
                  "refs/remotes/origin/${TEST_BRANCH}-target"

  test-when-ahead:
    name: "When Ahead of Base"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-test-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}

      - name: "Setup"
        id: setup
        shell: bash
        run: |-
          set -euo pipefail
          git checkout -b "${TEST_BRANCH}-target"
          git push origin "${TEST_BRANCH}-target"

          # Move target branch ahead of base branch
          echo "Test" >file.txt
          git add file.txt
          git commit -m "Add file"
          git push origin "${TEST_BRANCH}-target"

          printf "commit=%s\n" "$(git rev-parse HEAD)" >>"$GITHUB_OUTPUT"

      - name: "Remove local branches"
        shell: bash
        run: |-
          set -euo pipefail
          git fetch --depth=1 origin master
          git checkout master
          git branch -D "${TEST_BRANCH}" "${TEST_BRANCH}-target"

      - id: action
        uses: $/rebase-branch
        with:
          base: ${{ steps.test-branch.outputs.branch }}
          branch: ${{ steps.test-branch.outputs.branch }}-target
          create-branch: false

      - name: "Fetch and checkout rebased branch"
        shell: bash
        run: |-
          set -euo pipefail
          git fetch origin "${TEST_BRANCH}" "${TEST_BRANCH}-target"
          git checkout "refs/remotes/origin/${TEST_BRANCH}-target"

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Changes from target branch were kept"
              run: 'test -e file.txt'
              is: ok

            - name: "Target branch HEAD is unchanged"
              is: ok
              run: 'git rev-parse HEAD'
              is:
                - ok
                - equal: |-
                    ${{ steps.setup.outputs.commit }}

            - name: "Base branch is ancestor of target branch"
              is: ok
              run: |-
                git merge-base --is-ancestor \
                  "refs/remotes/origin/${TEST_BRANCH}" \
                  "refs/remotes/origin/${TEST_BRANCH}-target"

  test-when-same-commit:
    name: "When Up-to-date"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-test-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}

      - name: "Setup"
        id: setup
        shell: bash
        run: |-
          set -euo pipefail
          printf "commit=%s\n" "$(git rev-parse HEAD)" >>"$GITHUB_OUTPUT"
          git checkout -b "${TEST_BRANCH}-target"
          git push origin "${TEST_BRANCH}-target"

      - name: "Remove local branches"
        shell: bash
        run: |-
          set -euo pipefail
          git fetch --depth=1 origin master
          git checkout master
          git branch -D "${TEST_BRANCH}" "${TEST_BRANCH}-target"

      - id: action
        uses: $/rebase-branch
        with:
          base: ${{ steps.test-branch.outputs.branch }}
          branch: ${{ steps.test-branch.outputs.branch }}-target

      - name: "Fetch and checkout rebased branch"
        shell: bash
        run: |-
          set -euo pipefail
          git fetch origin "${TEST_BRANCH}" "${TEST_BRANCH}-target"
          git checkout "refs/remotes/origin/${TEST_BRANCH}-target"

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Target branch HEAD is unchanged"
              is: ok
              run: 'git rev-parse "refs/remotes/origin/${TEST_BRANCH}-target"'
              is:
                - ok
                - equal: |-
                    ${{ steps.setup.outputs.commit }}

            - name: "Base branch HEAD is unchanged"
              is: ok
              run: 'git rev-parse "refs/remotes/origin/${TEST_BRANCH}"'
              is:
                - ok
                - equal: |-
                    ${{ steps.setup.outputs.commit }}

  test-creates-branch:
    name: "When Branch Not Exists"
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        uses: $/create-test-branch/as-app
        with:
          ghapp-client-id: ${{ secrets.GHAPP_CLIENT_ID }}
          ghapp-private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}
          repository: ${{ env.TEST_REPO }}

      - name: "Remove local branches"
        shell: bash
        run: |-
          set -euo pipefail
          git fetch --depth=1 origin master
          git checkout master
          git branch -D "${TEST_BRANCH}"

      - id: action
        uses: $/rebase-branch
        with:
          base: ${{ steps.test-branch.outputs.branch }}
          branch: ${{ steps.test-branch.outputs.branch }}-target

      - name: "Run assertions"
        id: assert
        uses: $/actions-assert
        with:
          outputs: ${{ toJson(steps.action.outputs) }}
          asserts: |-
            - name: "Target branch was created"
              is: [ok, not empty]
              run: |-
                git fetch origin "${TEST_BRANCH}" "${TEST_BRANCH}-target" 1>&2
                git rev-parse "refs/remotes/origin/${TEST_BRANCH}-target"
                git rev-parse "refs/remotes/origin/${TEST_BRANCH}-target"'
